<div class="col-lg-2">
  <div class="form-group">
    <label>Ejercicio</label>
    <select class="select2" name="exercise_name">
      <option selected disabled>Selecciona Ejercicio</option>
      <optgroup label="Pectoral(superior)">
        <option value="Aperturas con mancuerna en banco inclinado">Aperturas con mancuerna en banco inclinado</option>
        <option value="Aperturas inclinadas con mancuernas en supinación">Aperturas inclinadas con mancuernas en supinación</option>
        <option value="Aperturas inclinadas en polea">Aperturas inclinadas en polea</option>
        <option value="Press de banca al cuello">Press de banca al cuello</option>
        <option value="Press de banca con barra y agarre cerrado">Press de banca con barra y agarre cerrado</option>
        <option value="Press inclinado con barra">Press inclinado con barra</option>
        <option value="Press inclinado con mancuernas">Press inclinado con mancuernas</option>
        <option value="Press inclinado en máquina de discos">Press inclinado en máquina de discos</option>
        <option value="Press inclinado en Multipower">Press inclinado en Multipower</option>
        <option value="Press inclinado mancuernas agarre martillo">Press inclinado mancuernas agarre martillo</option>
      </optgroup>
      <optgroup label="Pectoral(medio)">
        <option value="Aperturas circulares">Aperturas circulares</option>
        <option value="Aperturas con mancuerna a una mano">Aperturas con mancuerna a una mano</option>
        <option value="Aperturas con polea en banco plano">Aperturas con polea en banco plano</option>
        <option value="Aperturas de pecho en máquina">Aperturas de pecho en máquina</option>
        <option value="Aperturas en Peck-deck">Aperturas en Peck-deck</option>
        <option value="Aperturas planas con mancuernas">Aperturas planas con mancuernas</option>
        <option value="Aperturas planas en polea">Aperturas planas en polea</option>
        <option value="Cruces en polea">Cruces en polea</option>
        <option value="Cruces en polea baja">Cruces en polea baja</option>
        <option value="Flexiones">Flexiones</option>
        <option value="Flexiones a manos juntas">Flexiones a manos juntas</option>
        <option value="Flexiones con pies elevados">Flexiones con pies elevados</option>
        <option value="Fondos en máquina">Fondos en máquina</option>
        <option value="Fondos para pecho">Fondos para pecho</option>
        <option value="Press de banca con bandas elasticas">Press de banca con bandas elasticas</option>
        <option value="Press de banca con barra">Press de banca con barra</option>
        <option value="Press de banca con barra agarre ancho">Press de banca con barra agarre ancho</option>
        <option value="Press de banca en multipower">Press de banca en multipower</option>
        <option value="Press de pecho en máquina horizontal">Press de pecho en máquina horizontal</option>
        <option value="Press en banco plano con mancuernas">Press en banco plano con mancuernas</option>
        <option value="Press vertical en aparato">Press vertical en aparato</option>
        <option value="Pullover con barra">Pullover con barra</option>
        <option value="Pullover con mancuerna">Pullover con mancuerna</option>
      </optgroup>
      <optgroup label="Pectoral(inferior)">
        <option value="Aperturas con mancuernas en banco declinado">Aperturas con mancuernas en banco declinado</option>
        <option value="Press de banca declinado con barra agarre ancho">Press de banca declinado con barra agarre ancho</option>
        <option value="Press declinado con barra">Press declinado con barra</option>
        <option value="Press declinado con mancuernas">Press declinado con mancuernas</option>
        <option value="Press Declinado en Multipower">Press Declinado en Multipower</option>
      </optgroup>
      <optgroup label="Espalda(Dominadas y Jalones)">
        <option value="Dominadas">Dominadas</option>
        <option value="Dominadas agarre ancho">Dominadas agarre ancho</option>
        <option value="Dominadas agarre cerrado">Dominadas agarre cerrado</option>
        <option value="Dominadas tras nuca">Dominadas tras nuca</option>
        <option value="Jalones agarre cerrado (o jalón al pecho)">Jalones agarre cerrado (o jalón al pecho)</option>
        <option value="Jalones agarre V">Jalones agarre V</option>
        <option value="Jalones en máquina">Jalones en máquina</option>
        <option value="Jalones frontales">Jalones frontales</option>
        <option value="Jalones frontales con brazos rectos">Jalones frontales con brazos rectos</option>
        <option value="Jalones tras nuca">Jalones tras nuca</option>
      </optgroup>
      <optgroup label="Espalda(Remos)">
        <option value="Remo con barra">Remo con barra</option>
        <option value="Remo con barra a una mano">Remo con barra a una mano</option>
        <option value="Remo con barra agarre invertido">Remo con barra agarre invertido</option>
        <option value="Remo con mancuernas">Remo con mancuernas</option>
        <option value="Remo con mancuernas en banco inclinado">Remo con mancuernas en banco inclinado</option>
        <option value="Remo con mancuernas palmas enfrentadas">Remo con mancuernas palmas enfrentadas</option>
        <option value="Remo en barra T">Remo en barra T</option>
        <option value="Remo en máquina">Remo en máquina</option>
        <option value="Remo en máquina tumbado">Remo en máquina tumbado</option>
        <option value="Remo en multipower">Remo en multipower</option>
        <option value="Remo en polea sentado">Remo en polea sentado</option>
        <option value="Remo mancuerna a una mano">Remo mancuerna a una mano</option>
      </optgroup>
      <optgroup label="Espalda(Remos)">
        <option value="Buenos días con barra de pie">Buenos días con barra de pie</option>
        <option value="Buenos días con barra sentado">Buenos días con barra sentado</option>
        <option value="Hiperextensiones de espalda">Hiperextensiones de espalda</option>
        <option value="Peso Muerto">Peso Muerto</option>
        <option value="Peso Muerto estilo Sumo">Peso Muerto estilo Sumo</option>
        <option value="Peso muerto piernas rígidas con barra">Peso muerto piernas rígidas con barra</option>
        <option value="Peso muerto piernas rígidas con mancuernas">Peso muerto piernas rígidas con mancuernas</option>
        <option value="Peso muerto piernas rígidas en multipower">Peso muerto piernas rígidas en multipower</option>
        <option value="Superman">Superman</option>
      </optgroup>
      <optgroup label="Hombro(Deltoides Anterior)">
        <option value="Elevaciones frontales con balón medicinal">Elevaciones frontales con balón medicinal</option>
        <option value="Elevaciones frontales en banco inclinado">Elevaciones frontales en banco inclinado</option>
        <option value="Elevaciones frontales con barra">Elevaciones frontales con barra</option>
        <option value="Elevaciones frontales con disco">Elevaciones frontales con disco</option>
        <option value="Elevaciones frontales con mancuerna">Elevaciones frontales con mancuerna</option>
        <option value="Elevaciones frontales con mancuerna alterno">Elevaciones frontales con mancuerna alterno</option>
        <option value="Elevaciones frontales en polea a una mano">Elevaciones frontales en polea a una mano</option>
        <option value="Press cubano">Press cubano</option>
        <option value="Press de hombros en multipower">Press de hombros en multipower</option>    
      </optgroup>
      <optgroup label="Hombro (Deltoides Medio)">
        <option value="Elevaciones laterales">Elevaciones laterales</option>
        <option value="Elevaciones laterales a una mano">Elevaciones laterales a una mano</option>
        <option value="Elevación lateral inclinada">Elevación lateral inclinada</option>
        <option value="Elevaciones laterales a una mano banco inclinado">Elevaciones laterales a una mano banco inclinado</option>
        <option value="Elevaciones laterales sentado">Elevaciones laterales sentado</option>
        <option value="Elevaciones laterales en máquina">Elevaciones laterales en máquina</option>
        <option value="Elevaciones a una mano en polea">Elevaciones a una mano en polea</option>
        <option value="Press Arnold">Press Arnold</option>
        <option value="Press de hombros con mancuernas alterno">Press de hombros con mancuernas alterno</option>
        <option value="Press de hombro con mancuernas sentado">Press de hombro con mancuernas sentado</option>
        <option value="Press de hombros en máquina">Press de hombros en máquina</option>
        <option value="Press de hombros en polea">Press de hombros en polea</option>
        <option value="Press con mancuernas de pie">Press con mancuernas de pie</option>
        <option value="Press con mancuernas de pie a una mano">Press con mancuernas de pie a una mano</option>
        <option value="Press militar con barra sentado">Press militar con barra sentado</option>
        <option value="Press militar con barra de pie">Press militar con barra de pie</option>
        <option value="Press militar con agarre invertido en multipower">Press militar con agarre invertido en multipower</option>
        <option value="Remo al mentón con barra agarre abierto">Remo al mentón con barra agarre abierto</option>
        <option value="Remo al mentón en multipower">Remo al mentón en multipower</option>
      </optgroup>
      <optgroup label="Hombro (Deltoides Posterior)">
        <option value="Elevación posterior tumbado a una mano">Elevación posterior tumbado a una mano</option>
        <option value="Elevaciones posteriores tumbado">Elevaciones posteriores tumbado</option>
        <option value="Elevación posterior a una mano en polea">Elevación posterior a una mano en polea</option>
        <option value="Pájaros en banco inclinado">Pájaros en banco inclinado</option>
        <option value="Pájaros en polea sentado">Pájaros en polea sentado</option>
        <option value="Pájaros en polea de pie">Pájaros en polea de pie</option>
        <option value="Pájaros sentado con mancuernas">Pájaros sentado con mancuernas</option>
        <option value="Pájaros de pie con mancuernas">Pájaros de pie con mancuernas</option>
        <option value="Press tras nuca de pie con barra">Press tras nuca de pie con barra</option>
        <option value="Press tras nuca en multipower">Press tras nuca en multipower</option>
        <option value="Rotaciones externas (Rotadores)">Rotaciones externas (Rotadores)</option>
        <option value="Aperturas invertidas en contractora">Aperturas invertidas en contractora</option>
      </optgroup>
      <optgroup label="Hombro (Trapecio)">
        <option value="Encogimientos con barra">Encogimientos con barra</option>
        <option value="Encogimientos tras nuca con barra">Encogimientos tras nuca con barra</option>
        <option value="Encogimientos con mancuernas">Encogimientos con mancuernas</option>
        <option value="Encogimientos en multipower">Encogimientos en multipower</option>
        <option value="Encogimientos en polea">Encogimientos en polea</option>
        <option value="Remo al mentón con barra">Remo al mentón con barra</option>
        <option value="Remo al mentón con mancuernas">Remo al mentón con mancuernas</option>
        <option value="Remo al mentón en multipower">Remo al mentón en multipower</option>
        <option value="Remo al mentón en polea">Remo al mentón en polea</option>
        <option value="Remo al mentón en polea inclinado">Remo al mentón en polea inclinado</option>
      </optgroup>
      <optgroup label="Pierna (Cuádriceps)">
        <option value="Abductores en polea">Abductores en polea</option>
        <option value="Subir al banco con barra">Subir al banco con barra</option>
        <option value="Subir al banco con mancuernas">Subir al banco con mancuernas</option>
        <option value="Sentadilla con barra">Sentadilla con barra</option>
        <option value="Sentadilla con barra con piernas abiertas">Sentadilla con barra con piernas abiertas</option>
        <option value="Sentadilla frontal con barra">Sentadilla frontal con barra</option>
        <option value="Sentadilla Jefferson">Sentadilla Jefferson</option>
        <option value="Sentadilla Hack">Sentadilla Hack</option>
        <option value="Sentadilla Hack con barra">Sentadilla Hack con barra</option>
        <option value="Sentadilla Hack a una pierna">Sentadilla Hack a una pierna</option>
        <option value="Sentadilla en multipower">Sentadilla en multipower</option>
        <option value="Sentadilla en multipower piernas abiertas">Sentadilla en multipower piernas abiertas</option>
        <option value="Sentadilla Sissy">Sentadilla Sissy</option>
        <option value="Sentadillas con mancuerna">Sentadillas con mancuerna</option>
        <option value="Zancadas con barra">Zancadas con barra</option>
        <option value="Zancadas laterales con mancuernas">Zancadas laterales con mancuernas</option>
        <option value="Zancadas inversas con mancuernas">Zancadas inversas con mancuernas</option>
        <option value="Zancadas estáticas en multipower">Zancadas estáticas en multipower</option>
        <option value="Zancadas con mancuernas">Zancadas con mancuernas</option>
        <option value="Extensiones en máquina a una pierna">Extensiones en máquina a una pierna</option>
        <option value="Extensiones en máquina">Extensiones en máquina</option>
        <option value="Peso Muerto">Peso Muerto</option>
        <option value="Power Cleans">Power Cleans</option>
        <option value="Prensa Inclinada">Prensa Inclinada</option>
        <option value="Prensa Horizontal">Prensa Horizontal</option>
        <option value="Prensa vertical">Prensa vertical</option>
        <option value="Prensa Inclinada a una pierna">Prensa Inclinada a una pierna</option>
      </optgroup>
      <optgroup label="Pierna (Femoral y gluteos)">
        <option value="Curl femoral en balón de ejercicio">Curl femoral en balón de ejercicio</option>
          <option value="Elevaciones de glúteos en balón de ejercicio">Elevaciones de glúteos en balón de ejercicio</option>
          <option value="Elevaciones de piernas en balón de ejercicio">Elevaciones de piernas en balón de ejercicio</option>
          <option value="Extensiones de glúteos con cinta elástica">Extensiones de glúteos con cinta elástica</option>
          <option value="Extensiones de glúteos en polea">Extensiones de glúteos en polea</option>
          <option value="Femoral en máquina de pie">Femoral en máquina de pie</option>
          <option value="Femoral en máquina sentado">Femoral en máquina sentado</option>
          <option value="Femoral en máquina tumbado">Femoral en máquina tumbado</option>
          <option value="Femoral sentado en máquina a una pierna">Femoral sentado en máquina a una pierna</option>
          <option value="Femoral tumbado en máquina a una pierna">Femoral tumbado en máquina a una pierna</option>
          <option value="Levantar balón de ejercicio para glúteos">Levantar balón de ejercicio para glúteos</option>
          <option value="Patadas para glúteos">Patadas para glúteos</option>
          <option value="Peso muerto rumano">Peso muerto rumano</option>
          <option value="Peso muerto rumano con mancuernas">Peso muerto rumano con mancuernas</option>
          <option value="Peso muerto piernas rígidas">Peso muerto piernas rígidas</option>
          <option value="Peso muerto piernas rígidas con mancuernas">Peso muerto piernas rígidas con mancuernas</option>
          <option value="Peso muerto piernas rígidas en multipower">Peso muerto piernas rígidas en multipower</option>
          <option value="Prensa inclinada">Prensa inclinada</option>
          <option value="Puentes en suelo para glúteos">Puentes en suelo para glúteos</option>
          <option value="Sentadilla en multipower">Sentadilla en multipower</option>
          <option value="Sentadilla con mancuerna">Sentadilla con mancuerna</option>
          <option value="Subir al banco con mancuernas">Subir al banco con mancuernas</option>
          <option value="Zancadas inversas">Zancadas inversas</option>
          <option value="Zancadas con barra">Zancadas con barra</option>
          <option value="Zancadas caminando">Zancadas caminando</option>
          <option value="Zancadas con mancuernas">Zancadas con mancuernas</option>
          <option value="Abductores">Abductores</option>
          <option value="Buenos días con barra">Buenos días con barra</option>
      </optgroup>
      <optgroup label="Pierna (Gemelo)">
        <option value="Elevación de gemelo a un pie">Elevación de gemelo a un pie</option>
        <option value="Elevación de gemelo en máquina sentado">Elevación de gemelo en máquina sentado</option>
        <option value="Elevación de gemelo en máquina de pie">Elevación de gemelo en máquina de pie</option>
        <option value="Elevación de gemelos de pie con mancuernas">Elevación de gemelos de pie con mancuernas</option>
        <option value="Elevación de gemelos con mancuernas sentado">Elevación de gemelos con mancuernas sentado</option>
        <option value="Elevación de gemelos en máquina hack">Elevación de gemelos en máquina hack</option>
        <option value="Elevación de gemelos en máquina burro">Elevación de gemelos en máquina burro</option>
        <option value="Elevación de gemelos con barra sentado">Elevación de gemelos con barra sentado</option>
        <option value="Elevación de gemelos de pie con barra">Elevación de gemelos de pie con barra</option>
        <option value="Gemelo en prensa">Gemelo en prensa</option>
      </optgroup>
      <optgroup label="Biceps (con barra)">
        <option value="Curl con barra">Curl con barra</option>
        <option value="Curl de arrastre con barra">Curl de arrastre con barra</option>
        <option value="Curl con barra agarre cerrado">Curl con barra agarre cerrado</option>
        <option value="Curl con barra agarre ancho">Curl con barra agarre ancho</option>
        <option value="Curl con barra agarre invertido">Curl con barra agarre invertido</option>
        <option value="Curl con barra Z">Curl con barra Z</option>
        <option value="Curl con barra Z agarre cerrado">Curl con barra Z agarre cerrado</option>
        <option value="Curl con barra Z en banco predicador ">Curl con barra Z en banco predicador </option>
        <option value="Curl con barra Z concentrado">Curl con barra Z concentrado</option>
        <option value="Curl con barra tumbado sobre banco inclinado">Curl con barra tumbado sobre banco inclinado</option>
        <option value="Curl araña con barra Z">Curl araña con barra Z</option>
        <option value="Curl invertido con disco">Curl invertido con disco</option>
        <option value="Curl Forzado">Curl Forzado</option>
      </optgroup>
      <optgroup label="Biceps (con mancuernas)">
        <option value="Curl con mancuernas alterno de pie">Curl con mancuernas alterno de pie</option>
        <option value="Curl con mancuernas a dos manos de pie">Curl con mancuernas a dos manos de pie</option>
        <option value="Curl con mancuernas supinando de pie">Curl con mancuernas supinando de pie</option>
        <option value="Curl con mancuerna agarre martillo alterno de pie">Curl con mancuerna agarre martillo alterno de pie</option>
        <option value="Curl con mancuernas agarre martillo a dos manos de pie">Curl con mancuernas agarre martillo a dos manos de pie</option>
        <option value="Curl con mancuernas agarre martillo cruzado">Curl con mancuernas agarre martillo cruzado</option>
        <option value="Curl Zottman con mancuernas de pie">Curl Zottman con mancuernas de pie</option>
        <option value="Curl con mancuernas a dos manos sentado ">Curl con mancuernas a dos manos sentado </option>
        <option value="Curl con mancuernas alterno sentado (Próximamente.)">Curl con mancuernas alterno sentado (Próximamente.)</option>
        <option value="Curl con mancuernas supinándo sentado">Curl con mancuernas supinándo sentado</option>
        <option value="Curl con mancuernas alterno en banco inclinado">Curl con mancuernas alterno en banco inclinado</option>
        <option value="Curl con mancuernas a dos manos en banco inclinado">Curl con mancuernas a dos manos en banco inclinado</option>
        <option value="Curl con mancuernas supinándo en banco inclinado">Curl con mancuernas supinándo en banco inclinado</option>
        <option value="Curl con mancuernas agarre martillo en banco predicador">Curl con mancuernas agarre martillo en banco predicador</option>
        <option value="Curl con mancuernas a dos manos en banco predicador">Curl con mancuernas a dos manos en banco predicador</option>
        <option value="Curl con mancuerna a una mano en banco predicador">Curl con mancuerna a una mano en banco predicador</option>
        <option value="Curl Zottman con mancuerna en banco predicador">Curl Zottman con mancuerna en banco predicador</option>
        <option value="Curl con mancuerna a una mano sobre banco inclinado (Tipo Scott)">Curl con mancuerna a una mano sobre banco inclinado (Tipo Scott)</option>
        <option value="Curl de concentración">Curl de concentración</option>
        <option value="Curl con mancuernas tumbado en banco">Curl con mancuernas tumbado en banco</option>
      </optgroup>
      <optgroup label="Biceps (polea y máquina)">
        <option value="Curl polea de pie">Curl polea de pie</option>
        <option value="Curl en polea alta">Curl en polea alta</option>
        <option value="Curl en polea en banco inclinado">Curl en polea en banco inclinado</option>
        <option value="Curl polea alta tumbado en banco">Curl polea alta tumbado en banco</option>
        <option value="Curl polea a dos manos">Curl polea a dos manos</option>
        <option value="Curl polea tumbado en suelo">Curl polea tumbado en suelo</option>
        <option value="Curl polea a un brazo">Curl polea a un brazo</option>
        <option value="Curl polea con cuerda agarre martillo">Curl polea con cuerda agarre martillo</option>
        <option value="Curl polea en banco predicador">Curl polea en banco predicador</option>
        <option value="Curl concentrado en polea">Curl concentrado en polea</option>
        <option value="Curl en máquina">Curl en máquina</option>
        <option value="Curl en máquina tipo predicador">Curl en máquina tipo predicador</option>
      </optgroup>
      <optgroup label="Tríceps">
        <option value="Flexiones con manos juntas">Flexiones con manos juntas</option>
        <option value="Fondos">Fondos</option>
        <option value="Fondos en máquina para tríceps">Fondos en máquina para tríceps</option>
        <option value="Fondos entre bancos">Fondos entre bancos</option>
        <option value="Press de banca agarre cerrado">Press de banca agarre cerrado</option>
        <option value="Press de banca agarre cerrado e inverso">Press de banca agarre cerrado e inverso</option>
        <option value="Press de banca agarre cerrado en multipower">Press de banca agarre cerrado en multipower</option>
        <option value="Press de tríceps tumbado">Press de tríceps tumbado</option>
        <option value="Press Francés">Press Francés</option>
        <option value="Extensión con barra por detrás de la cabeza tumbado">Extensión con barra por detrás de la cabeza tumbado</option>
        <option value="Extension con mancuerna a una mano sentado">Extension con mancuerna a una mano sentado</option>
        <option value="Extensiones a una mano en polea baja">Extensiones a una mano en polea baja</option>
        <option value="Extensiones con barra por encima de la cabeza">Extensiones con barra por encima de la cabeza</option>
        <option value="Extensiones con barra sentado por encima de la cabeza">Extensiones con barra sentado por encima de la cabeza</option>
        <option value="Extensiones con mancuerna a un brazo">Extensiones con mancuerna a un brazo</option>
        <option value="Extensiones con mancuerna a una mano de pie">Extensiones con mancuerna a una mano de pie</option>
        <option value="Extensiones con mancuerna a una mano tumbado y agarre prono">Extensiones con mancuerna a una mano tumbado y agarre prono</option>
        <option value="Extensiones con mancuerna a una mano tumbado y agarre supino">Extensiones con mancuerna a una mano tumbado y agarre supino</option>
        <option value="Extensiones con mancuerna por encima de la cabeza">Extensiones con mancuerna por encima de la cabeza</option>
        <option value="Extensiones con mancuerna sentado por encima de la cabeza">Extensiones con mancuerna sentado por encima de la cabeza</option>
        <option value="Extensiones con mancuerna tumbado">Extensiones con mancuerna tumbado</option>
        <option value="Extensiones con mancuernas a dos manos de pie">Extensiones con mancuernas a dos manos de pie</option>
        <option value="Extensiones con mancuernas sentado a dos manos">Extensiones con mancuernas sentado a dos manos</option>
        <option value="Extensiones con mancuernas tumbado y agarre supino">Extensiones con mancuernas tumbado y agarre supino</option>
        <option value="Extensiones con toalla">Extensiones con toalla</option>
        <option value="Extensiones de concentracion en polea arrodillado">Extensiones de concentracion en polea arrodillado</option>
        <option value="Extensiones de triceps con polea en banco inclinado">Extensiones de triceps con polea en banco inclinado</option>
        <option value="Extensiones de tríceps en máquina">Extensiones de tríceps en máquina</option>
        <option value="Extensiones declinadas con barra Z">Extensiones declinadas con barra Z</option>
        <option value="Extensiones declinadas con mancuernas">Extensiones declinadas con mancuernas</option>
        <option value="Extensiones en banco inclinado con barra Z">Extensiones en banco inclinado con barra Z</option>
        <option value="Extensiones en polea a un brazo">Extensiones en polea a un brazo</option>
        <option value="Extensiones en polea arrodillado">Extensiones en polea arrodillado</option>
        <option value="Extensiones en polea baja tumbado">Extensiones en polea baja tumbado</option>
        <option value="Extensiones en polea tumbado">Extensiones en polea tumbado</option>
        <option value="Extensiones sobre la cabeza en polea con cuerda">Extensiones sobre la cabeza en polea con cuerda</option>
        <option value="Jalones con barra recta">Jalones con barra recta</option>
        <option value="Jalones con barra V">Jalones con barra V</option>
        <option value="Jalones con cuerda">Jalones con cuerda</option>
        <option value="Jalones en polea con agarre inverso">Jalones en polea con agarre inverso</option>
        <option value="Patadas con mancuerna">Patadas con mancuerna</option>
        <option value="Patadas de triceps en polea">Patadas de triceps en polea</option>
      </optgroup>
      <optgroup label="Abdomen (inferior)">
        <option value="Elevaciones de cadera con rodillas dobladas">Elevaciones de cadera con rodillas dobladas</option>
        <option value="Elevaciones de piernas colgado">Elevaciones de piernas colgado</option>
        <option value="Elevaciones de piernas colgado piernas estiradas">Elevaciones de piernas colgado piernas estiradas</option>
        <option value="Elevaciones de piernas con balón medicinal">Elevaciones de piernas con balón medicinal</option>
        <option value="Elevaciones de piernas en banco plano">Elevaciones de piernas en banco plano</option>
        <option value="Elevaciones de piernas en paralelas">Elevaciones de piernas en paralelas</option>
        <option value="Elevaciones de rodillas a la barbilla colgado">Elevaciones de rodillas a la barbilla colgado</option>
        <option value="Elevaciones de rodillas a la cabeza">Elevaciones de rodillas a la cabeza</option>
        <option value="Encogimientos en banco declinado">Encogimientos en banco declinado</option>
        <option value="Encogimientos en UVE">Encogimientos en UVE</option>
        <option value="Encogimientos invertidos">Encogimientos invertidos</option>
        <option value="Encogimientos invertidos en balón de ejercicio">Encogimientos invertidos en balón de ejercicio</option>
        <option value="Encogimientos invertidos en banco declinado">Encogimientos invertidos en banco declinado</option>
        <option value="Encogimientos invertidos tumbado">Encogimientos invertidos tumbado</option>
        <option value="Encogimientos mano a pierna con peso">Encogimientos mano a pierna con peso</option>
        <option value="Pull-in con balón de ejercicio">Pull-in con balón de ejercicio</option>
        <option value="Pull-in en banco plano">Pull-in en banco plano</option>
        <option value="Tijeras de piernas">Tijeras de piernas</option>
      </optgroup>
      <optgroup label="Abodmen (superior y zona media)">
        <option value="Elevaciones de glúteos para abdomen">Elevaciones de glúteos para abdomen</option>
        <option value="Encogimientos abdominales con brazos en cruz">Encogimientos abdominales con brazos en cruz</option>
        <option value="Encogimientos abdominales con brazos rectos">Encogimientos abdominales con brazos rectos</option>
        <option value="Encogimientos abdominales dedos a pies">Encogimientos abdominales dedos a pies</option>
        <option value="Encogimientos abdominales en suelo">Encogimientos abdominales en suelo</option>
        <option value="Encogimientos con balón medicinal en balón de ejercicio">Encogimientos con balón medicinal en balón de ejercicio</option>
        <option value="Encogimientos con barra a las rodillas">Encogimientos con barra a las rodillas</option>
        <option value="Encogimientos con manos por encima de la cabeza">Encogimientos con manos por encima de la cabeza</option>
        <option value="Encogimientos con piernas en balón de ejercicio">Encogimientos con piernas en balón de ejercicio</option>
        <option value="Encogimientos en balón de ejercicio">Encogimientos en balón de ejercicio</option>
        <option value="Encogimientos en máquina">Encogimientos en máquina</option>
        <option value="Encogimientos en polea">Encogimientos en polea</option>
        <option value="Encogimientos tocando dedos de los pies">Encogimientos tocando dedos de los pies</option>
        <option value="Rodar con la barra">Rodar con la barra</option>
      </optgroup>
      <optgroup label="Abdomen (lateral)">
        <option value="Bicicleta para oblicuos">Bicicleta para oblicuos</option>
        <option value="Elevaciones de piernas para oblicuos tumbado">Elevaciones de piernas para oblicuos tumbado</option>
        <option value="Elevaciones de rodillas para oblicuos colgado">Elevaciones de rodillas para oblicuos colgado</option>
        <option value="Encogimiento lateral con barra de pie">Encogimiento lateral con barra de pie</option>
        <option value="Encogimiento lateral con mancuerna de pie">Encogimiento lateral con mancuerna de pie</option>
        <option value="Encogimientos con codo a rodilla contraria">Encogimientos con codo a rodilla contraria</option>
        <option value="Encogimientos laterales dedos a los tobillos">Encogimientos laterales dedos a los tobillos</option>
        <option value="Encogimientos para oblicuos">Encogimientos para oblicuos</option>
        <option value="Encogimientos para oblicuos en banco declinado">Encogimientos para oblicuos en banco declinado</option>
        <option value="Encogimientos para oblicuos tumbado de lado">Encogimientos para oblicuos tumbado de lado</option>
        <option value="Encogimientos para oblicuos en polea">Encogimientos para oblicuos en polea</option>
        <option value="Giros con barra para oblicuos sentado">Giros con barra para oblicuos sentado</option>
        <option value="Giros con disco para oblicuos">Giros con disco para oblicuos</option>
        <option value="Giros para oblicuos">Giros para oblicuos</option>
        <option value="Inclinación lateral en polea">Inclinación lateral en polea</option>
        <option value="Press Pallof">Press Pallof</option>
      </optgroup>
    </select>
  </div>
</div>
